<form action="loginUser.php" method="post" class="w-40" enctype="multipart/form-data">
    <h2 mt-4 ml-4 ><?=$message?></h2>
    <div class='d-flex flex-column mt-3 ml-4'>
        <label for="title">Email</label>
        <input type="text" id="email" name="email" class="rounded">
    </div>
    <div class='d-flex flex-column mt-3 ml-4'>
        <label for="title">Mot de passe</label>
        <input type="password" id="password" name="password" class="rounded">
    </div>
    <div class='mt-4 ml-4'>
    <button class="btn btn-secondary my-2 my-sm-0" type="submit">se connecter</button>
    </div>
</form>
